In [4]:
from torch_dataset import FiberGraphDataset
import torch
import numpy as np
ds = FiberGraphDataset(r'C:\Users\pablo\GitHub\tfm_prg\tractoinferno_graphs\testset')

# Crear un diccionario para contar las fibras de cada tipo
count_fibras = {}

# Recorrer el dataset y contar las fibras de cada tipo
for idx, suj in enumerate(ds):
    print(f"Procesando sujeto {idx+1}/{len(ds)}")
    labels = suj.y
    # Convertir a numpy
    labels = labels.to('cpu')
    labels = labels.numpy()
    # Contar las fibras de cada tipo de la forma mas eficiente
    unique, counts = np.unique(labels, return_counts=True)
    print(unique, counts)
    for tipo, count in zip(unique, counts):
        if tipo in count_fibras:
            count_fibras[tipo] += count
        else:
            count_fibras[tipo] = count

    

# Imprimir el resultado
for tipo, count in count_fibras.items():
    print(f"Tipo {tipo}: {count} fibras")


Procesando sujeto 1/29
[ 0  1  2  3  4  6  7  8  9 10 17 18 20 21 22 23 28 29] [  9725  34378  96179 189374 108761 144872  10309   7996  59082  30574
  42002  52448   1205    674  34826     57   4097  10932]
Procesando sujeto 2/29
[ 0  1  2  3  4  5  6  7  8  9 10 17 18 19 20 21 22 23 24 25 26 27 28 29
 30 31] [ 18375    499 128543 225817  79500 134682 239937  23149  12672  59878
  48062  11633  11294  12319   4573    631  18863  42181  11604  13272
  65734  79627   1737   5373    166    541]
Procesando sujeto 3/29
[ 0  1  2  3  4  5  6  7  8 17 18 20 21 22 23 24 25 26 27 28 29 30 31] [ 30264   7123  61188 155337  46594  72995 102770  17659  12537  18070
   9641    402   6636   5798  16388  14570  15744  33648  36120    654
  14565    219    664]
Procesando sujeto 4/29
[ 0  1  3  4  9 10 11 12 15 16 17 18 20 21 24 25 26 27 28 29 30 31] [11530 11751 90354 82274 56890 19466 42501 51926 44836 46131 20951 36522
   894  1850 25740  4836 50800 63621  1908 22287   482   811]
Procesando sujeto

In [6]:
# Ordenar el diccionario por keys
count_fibras = dict(sorted(count_fibras.items()))
count_fibras

{0: 746528,
 1: 329896,
 2: 2793503,
 3: 5128144,
 4: 2059468,
 5: 2765610,
 6: 3367322,
 7: 302274,
 8: 236299,
 9: 1263593,
 10: 988040,
 11: 659802,
 12: 716805,
 13: 569,
 14: 254,
 15: 696934,
 16: 730783,
 17: 1160519,
 18: 979649,
 19: 978293,
 20: 371638,
 21: 456242,
 22: 480974,
 23: 304006,
 24: 540280,
 25: 507532,
 26: 1308236,
 27: 1384632,
 28: 230113,
 29: 558167,
 30: 165851,
 31: 259382}

In [8]:
def get_streamline_weights():
    streamline_count = {0: 746528,
                        1: 329896,
                        2: 2793503,
                        3: 5128144,
                        4: 2059468,
                        5: 2765610,
                        6: 3367322,
                        7: 302274,
                        8: 236299,
                        9: 1263593,
                        10: 988040,
                        11: 659802,
                        12: 716805,
                        13: 569,
                        14: 254,
                        15: 696934,
                        16: 730783,
                        17: 1160519,
                        18: 979649,
                        19: 978293,
                        20: 371638,
                        21: 456242,
                        22: 480974,
                        23: 304006,
                        24: 540280,
                        25: 507532,
                        26: 1308236,
                        27: 1384632,
                        28: 230113,
                        29: 558167,
                        30: 165851,
                        31: 259382}
    weights = []
    for tipo, count in count_fibras.items():
        weights.append(1/count)
    weights = torch.tensor(weights)
    weights = weights/weights.sum()
    return weights

# streamline_count = {0: 746528,
#                     1: 329896,
#                     2: 2793503,
#                     3: 5128144,
#                     4: 2059468,
#                     5: 2765610,
#                     6: 3367322,
#                     7: 302274,
#                     8: 236299,
#                     9: 1263593,
#                     10: 988040,
#                     11: 659802,
#                     12: 716805,
#                     13: 569,
#                     14: 254,
#                     15: 696934,
#                     16: 730783,
#                     17: 1160519,
#                     18: 979649,
#                     19: 978293,
#                     20: 371638,
#                     21: 456242,
#                     22: 480974,
#                     23: 304006,
#                     24: 540280,
#                     25: 507532,
#                     26: 1308236,
#                     27: 1384632,
#                     28: 230113,
#                     29: 558167,
#                     30: 165851,
#                     31: 259382}


# # Crear weigths para el loss
# weights = []
# for tipo, count in count_fibras.items():
#     weights.append(1/count)
# weights = torch.tensor(weights)
# weights = weights/weights.sum()
weights = get_streamline_weights()
weights

tensor([2.3296e-04, 5.2717e-04, 6.2255e-05, 3.3913e-05, 8.4444e-05, 6.2883e-05,
        5.1646e-05, 5.7534e-04, 7.3598e-04, 1.3763e-04, 1.7602e-04, 2.6358e-04,
        2.4262e-04, 3.0564e-01, 6.8469e-01, 2.4954e-04, 2.3798e-04, 1.4986e-04,
        1.7752e-04, 1.7777e-04, 4.6796e-04, 3.8118e-04, 3.6158e-04, 5.7206e-04,
        3.2189e-04, 3.4266e-04, 1.3294e-04, 1.2560e-04, 7.5576e-04, 3.1157e-04,
        1.0486e-03, 6.7048e-04], dtype=torch.float64)